# docker-compose.yml

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    env_file:
      - ./.env
    # We will name the container to make it easy to find for the proxy
    container_name: vipps_test_app_backend
    expose:
      - "8000"
    # Connect it to the same external network your reverse proxy uses
    networks:
      - nginxproxymanager_default

volumes:
  db_data:

networks:
  nginxproxymanager_default:
    external: true